% SOLVESUDOKUIMAGE_CODEGEN_SCRIPT solveSudokuImage_codegen からダイナミック ライブラリ
%  solveSudokuImage_codegen を生成します。
% 
% プロジェクト 'solveSudokuImage_codegen.prj' から 05-Dec-2021 に生成されたスクリプトです。
% 
% CODER、CODER.CONFIG、CODER.TYPEOF、CODEGEN も参照してください。

%% クラス 'coder.EmbeddedCodeConfig' の構成オブジェクトを作成します。
cfg = coder.config('dll','ecoder',true);
cfg.TargetLang = 'C++';
cfg.GenerateReport = true;
cfg.ReportPotentialDifferences = false;
cfg.PostCodeGenCommand = 'wasm.coder.postcodegen.addCLinkage(buildInfo); wasm.coder.postcodegen.registerExportedFunctions(buildInfo)';
cfg.Toolchain = 'Emscripten v2.0.32 | gmake (64-bit Windows)';
cfg.BuildConfiguration = 'Specify';
cfg.MaxIdLength = 1024;
cfg.CustomToolchainOptions = { 'C Compiler', ...
                               '-c -Wall -O0', ...
                               'Linker', ...
                               '-s DEMANGLE_SUPPORT=1', ...
                               'Shared Library Linker', ...
                               '', ...
                               'C++ Compiler', ...
                               '-c -Wall -std=c++17 -O0', ...
                               'C++ Linker', ...
                               '-s DEMANGLE_SUPPORT=1', ...
                               'C++ Shared Library Linker', ...
                               '-s INITIAL_MEMORY=205914112', ...
                               'Archiver', ...
                               '', ...
                               'Download', ...
                               '', ...
                               'Execute', ...
                               '', ...
                               'Make Tool', ...
                               '-j32 -f $(MAKEFILE)' };
cfg.HardwareImplementation.ProdHWDeviceType = 'Google->V8 Engine';
cfg.HardwareImplementation.TargetHWDeviceType = 'Google->V8 Engine';

% Create a configuration object of class 'coder.DeepLearningConfigBase'.
cfg.DeepLearningConfig = coder.DeepLearningConfig('TargetLibrary', 'none');

%% エントリ ポイント 'solveSudokuImage_codegen' の引数のタイプを定義します。
ARGS = cell(1,1);
ARGS{1} = cell(1,1);
ARGS{1}{1} = coder.typeof(uint8(0),[1687500    1]);

%% MATLAB Coder を起動します。
codegen -config cfg solveSudokuImage_codegen -args ARGS{1}

